name: Render Preview Deploy
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  deployments: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Added environment to ensure access to environment-specific secrets if any
    environment: preview
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          api_key: "${{ secrets.RENDER_API_KEY }}"
          service_id: srv-d67s1b7pm1nc738lvm80
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          github_deployment: true
          deployment_environment: 'preview'
